CREATE COLUMN TABLE "11391074_1"."HANA_TRAINING::USERNAME"(
	"USERNUM" INTEGER,
	"USERNAME" NVARCHAR(50),
	"PASSWORD" NVARCHAR(100),
	"FULLNAME" NVARCHAR(100),
	PRIMARY KEY(
		"USERNUM"
	)
)
UNLOAD PRIORITY 5 AUTO MERGE;
