--- SP_CREATE_EMPLOYEE
CREATE LOCAL TEMPORARY TABLE #TempTable5 (
  SAPNO INTEGER,
  EMPEID NVARCHAR(50),
  FIRSTNAME NVARCHAR(100),
  LASTNAME NVARCHAR(100),
  BIRTHDATE DATE,
  AGE INTEGER,
  HIREDATE DATE,
  DELETEFLAG NVARCHAR(1)
);

INSERT INTO #TempTable5 VALUES  (10018, '10101',' John', 'Cruz', '2000-10-09', '20', '2024-09-01', '0');

CALL "11391074_1"."HANA_TRAINING.procedure::SP_CREATE_EMPLOYEE"(IP_ROW => #TempTable5 /*<TABLE_TYPE>*/,OP_MESSAGE => ?)

--- SP_UPDATE_EMPLOYEE
CREATE LOCAL TEMPORARY TABLE #TempTable1 (
    SAPNO INTEGER,
    LASTNAME NVARCHAR(100)
);

INSERT INTO #TempTable1 (SAPNO, LASTNAME) VALUES  (10017, 'Zurbano');

CALL "11391074_1"."HANA_TRAINING.procedure::SP_UPDATE_EMPLOYEE"(IP_ROW => #TempTable1 /*<TABLE_TYPE>*/,OP_MESSAGE => ?)

--- SP_DELETE_EMPLOYEE
CREATE LOCAL TEMPORARY TABLE #TempTable2 (
    SAPNO INTEGER
);

INSERT INTO #TempTable2 (SAPNO) VALUES  (10017);

CALL "11391074_1"."HANA_TRAINING.procedure::SP_DELETE_EMPLOYEE"(IP_ROW => #TempTable2 /*<TABLE_TYPE>*/,OP_MESSAGE => ?)

--- SP_READ_EMPLOYEE
CALL "11391074_1"."HANA_TRAINING.procedure::SP_READ_EMPLOYEE"(IP_SAPNO => 10017 /*<INTEGER>*/,OP_TABLE => ?)

--- SP_CREATE_SKILLSET
CREATE LOCAL TEMPORARY TABLE #TempTable7 (
	SAPNO INTEGER,
	SKILLID INTEGER,
	PROFLEVEL NVARCHAR(2),
	DATESTART NVARCHAR(500),
	DATEEND NVARCHAR(500),
	DELETEFLAG NVARCHAR(1)
);

INSERT INTO #TempTable7 VALUES  (10018, 1, 'P2', '2024-10-09', '2024-11-01', '0');

CALL "11391074_1"."HANA_TRAINING.procedure::SP_CREATE_SKILLSET"(IP_ROW => #TempTable7 /*<TABLE_TYPE>*/,OP_MESSAGE => ?)


--- SP_UPDATE_SKILLSET
CREATE LOCAL TEMPORARY TABLE #TempTable8 (
    SAPNO INTEGER,
    PROFLEVEL NVARCHAR(100)
);

INSERT INTO #TempTable8 (SAPNO, PROFLEVEL) VALUES  (10018, 'P1');

CALL "11391074_1"."HANA_TRAINING.procedure::SP_UPDATE_SKILLSET"(IP_ROW => #TempTable8 /*<TABLE_TYPE>*/,OP_MESSAGE => ?)

--- SP_DELETE_SKILLSET
CREATE LOCAL TEMPORARY TABLE #TempTable9 (
    SAPNO INTEGER
);

INSERT INTO #TempTable9 (SAPNO) VALUES  (10018);

CALL "11391074_1"."HANA_TRAINING.procedure::SP_DELETE_SKILLSET"(IP_ROW => #TempTable9 /*<TABLE_TYPE>*/,OP_MESSAGE => ?)

--- SP_READ_SKILLSET
CALL "11391074_1"."HANA_TRAINING.procedure::SP_READ_SKILLSET"(IP_SAPNO => 10018 /*<INTEGER>*/,OP_TABLE => ?)