--- 1.
SELECT FIRSTNAME, LASTNAME FROM "11391074_1"."HANA_TRAINING::TB_EMPLOYEE" WHERE SAPNO IN (
SELECT SAPNO FROM "11391074_1"."HANA_TRAINING::TB_SKILLSET" WHERE SKILLID IN (
SELECT SKILLID FROM "11391074_1"."HANA_TRAINING::TB_SKILL_INFO" WHERE SKILLNAME IN ('SAP HANA', 'SAP UI5')))
AND DELETEFLAG != '1'

--- 2.
SELECT PROJECT.SAPNO, EMPLOYEE.FIRSTNAME || ' ' || EMPLOYEE.LASTNAME AS EMPLOYEENAME, SKILLINFO.SKILLNAME, PROJECT.MANAGERSAPNO, PROJECTINFO.PROJECTNAME, PROJECT.DELETEFLAG
FROM "11391074_1"."HANA_TRAINING::TB_PROJECT" AS PROJECT
INNER JOIN "11391074_1"."HANA_TRAINING::TB_EMPLOYEE" AS EMPLOYEE
ON PROJECT.SAPNO = EMPLOYEE.SAPNO
INNER JOIN "11391074_1"."HANA_TRAINING::TB_MANAGER" AS MANAGER
ON PROJECT.MANAGERSAPNO = MANAGER.SAPNO
INNER JOIN "11391074_1"."HANA_TRAINING::TB_PROJECTID_INFO" AS PROJECTINFO
ON PROJECT.PROJECTID = PROJECTINFO.PROJECTID
INNER JOIN "11391074_1"."HANA_TRAINING::TB_SKILL_INFO" AS SKILLINFO
ON PROJECT.SKILLID = SKILLINFO.SKILLID
WHERE PROJECT.DELETEFLAG = '0'

--- 3.
SELECT COUNT(SAPNO) FROM "11391074_1"."HANA_TRAINING::TB_PROJECT" GROUP BY MANAGERSAPNO

--- 4. 
SELECT EMPLOYEE.SAPNO, EMPLOYEE.FIRSTNAME || ' ' || EMPLOYEE.LASTNAME AS EMPLOYEENAME, PROJECTINFO.PROJECTNAME
FROM "11391074_1"."HANA_TRAINING::TB_PROJECT" AS PROJECT
INNER JOIN "11391074_1"."HANA_TRAINING::TB_PROJECTID_INFO" AS PROJECTINFO
ON PROJECT.PROJECTID = PROJECTINFO.PROJECTID
INNER JOIN "11391074_1"."HANA_TRAINING::TB_SKILL_INFO" AS SKILLINFO
ON PROJECT.SKILLID = SKILLINFO.SKILLID
INNER JOIN "11391074_1"."HANA_TRAINING::TB_EMPLOYEE" AS EMPLOYEE
ON EMPLOYEE.SAPNO = PROJECT.SAPNO
WHERE SKILLINFO.SKILLNAME = 'SAP HANA'

--- 5.
SELECT EMPLOYEE.SAPNO, EMPLOYEE.FIRSTNAME || ' ' || EMPLOYEE.LASTNAME AS EMPLOYEENAME, PROJECTINFO.PROJECTNAME
FROM "11391074_1"."HANA_TRAINING::TB_PROJECT" AS PROJECT
INNER JOIN "11391074_1"."HANA_TRAINING::TB_PROJECTID_INFO" AS PROJECTINFO
ON PROJECT.PROJECTID = PROJECTINFO.PROJECTID
INNER JOIN "11391074_1"."HANA_TRAINING::TB_MANAGER" AS MANAGER
ON PROJECT.MANAGERSAPNO = MANAGER.SAPNO
INNER JOIN "11391074_1"."HANA_TRAINING::TB_EMPLOYEE" AS EMPLOYEE
ON PROJECT.SAPNO = EMPLOYEE.SAPNO
WHERE EMPLOYEE.HIREDATE BETWEEN ('2013-12-01') AND ('2014-08-31')